# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Functional

on:
  push:
    branches: [ "test-infra-functional" ]
  pull_request:
    branches: [ "test-infra-functional" ]

permissions:
  contents: read

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          git fetch && git pull
          pipenv sync
      - name: functional
        run: |
          pipenv run python -m pytest enviro_server/tests/tasks_test.py
