# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: functional

on:
  push:
    branches: [ master, "test/*", "feature/*" ]
  pull_request:
    branches: [ master, "test/*", "feature/*" ]

permissions:
  contents: read

jobs:
  functional-testing:
    runs-on: self-hosted
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: git
        run: |
          git fetch && git checkout ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} && git pull origin ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} --rebase
      - name: sync
        run: |
          pipenv sync
      - name: tasks
        run: |
          pipenv run python -m pytest enviro_server/tests/functional/tasks_test.py
      - name: authentication
        run: |
          pipenv run python -m pytest enviro_server/tests/functional/auth_tests.py
